source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yunhaiwu/ios-wj-framework-cocoapods-specs.git'
platform :ios, '7.0'

inhibit_all_warnings!

target :'WJCacheAPI-example' do

pod 'WJCommon/Core'
pod 'WJLoggingAPI'
pod 'WJConfig'

end
